import os
import requests
import datetime
import random

script_dir = os.path.dirname(os.path.abspath(__file__))
POSTS_DIR = os.path.join(script_dir, '..', 'source', '_posts')

def get_daily_quote():
    """从金山词霸获取每日一句"""
    try:
        url = "http://open.iciba.com/dsapi/"
        res = requests.get(url, timeout=5).json()
        return res['content'], res['note'], res['picture2']
    except:
        return ("Stay hungry, stay foolish.", "求知若饥，虚心若愚。",
                "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1350&q=80")


def create_markdown(ai_content):
    """根据 AI 生成的内容创建 Markdown 文件"""
    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")

    quote_en, quote_cn, quote_img = get_daily_quote()

    if not ai_content:
        print("No AI content provided, skipping.")
        return

    topic = ai_content.get('topic_display', 'English Learning')
    vocabs = ai_content.get('vocab_list', [])
    reading = ai_content.get('reading', {})

    # 构建单词表
    vocab_md = ""
    for v in vocabs:
        vocab_md += f"""
- **{v.get('word', '')}** `/{v.get('ipa', '')}/`
  - 🇺🇸 {v.get('en_def', '')}
  - 🇨🇳 {v.get('cn_def', '')}
  - 📝 *{v.get('sentence', '')}*
"""

    md_content = f"""---
title: "🌍 Daily English: {reading.get('title', 'Untitled')} | {date_str}"
date: {now.strftime('%Y-%m-%d %H:%M:%S')}
categories: English Learning
tags: [English, {topic}, Vocabulary, Reading]
---

## 🖼️ Part 1: Daily Quote

![]({quote_img})

> **"{quote_en}"**
>
> {quote_cn}

---

## 🔑 Part 2: Vocabulary Builder (10 Words)

Here are 10 key words selected from today's reading on **{topic}**:

{vocab_md}

---

## 📖 Part 3: Deep Reading

### {reading.get('title', 'Reading')}

{reading.get('content', '')}

---

### 💡 Language Highlights

{reading.get('analysis', '')}

---

*(Content generated by AI; Quote source: Iciba)*
"""

    filename = f"{date_str}-daily-english.md"
    filepath = os.path.join(POSTS_DIR, filename)

    if not os.path.exists(filepath):
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        print(f"✅ Generated: {filename}")
        return filepath
    else:
        print(f"⚠️  File {filename} already exists. Skipping.")
        return None


if __name__ == "__main__":
    import sys
    import json

    # 从 stdin 读取 AI 生成的内容（JSON）
    try:
        data = json.load(sys.stdin)
        result = create_markdown(data)
        if result:
            print(f"FILE:{result}")
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
