const { getDb } = require('../database/schema');
const { v4: uuidv4 } = require('uuid');

module.exports = {
  queue({ page = 1, pageSize = 50, status = 'review_pending' } = {}) { const db = getDb(); const items = db.prepare(`SELECT a.*, t.title as topic_title, u.username as creator_name FROM articles a LEFT JOIN topics t ON a.topic_id = t.id LEFT JOIN users u ON a.created_by = u.id WHERE a.status = ? ORDER BY a.updated_at DESC LIMIT ? OFFSET ?`).all(status, pageSize, (page - 1) * pageSize); const total = db.prepare('SELECT COUNT(*) as c FROM articles WHERE status = ?').get(status); return { items, total: total.c, page, pageSize }; },
  submitForReview(articleId, userId) { const db = getDb(); db.prepare("UPDATE articles SET status = 'review_pending', updated_at = datetime('now','localtime') WHERE id = ?").run(articleId); const logId = uuidv4(); db.prepare('INSERT INTO review_log (id, article_id, reviewer_id, action) VALUES (?, ?, ?, ?)').run(logId, articleId, userId || null, 'submit'); return { ok: true }; },
  approve(articleId, userId, comment) { const db = getDb(); db.prepare("UPDATE articles SET status = 'review_approved', reviewed_by = ?, review_comment = ?, updated_at = datetime('now','localtime') WHERE id = ?").run(userId || null, comment || '', articleId); const logId = uuidv4(); db.prepare('INSERT INTO review_log (id, article_id, reviewer_id, action, comment) VALUES (?, ?, ?, ?, ?)').run(logId, articleId, userId || null, 'approve', comment || ''); return { ok: true }; },
  reject(articleId, userId, comment) { const db = getDb(); db.prepare("UPDATE articles SET status = 'review_rejected', reviewed_by = ?, review_comment = ?, updated_at = datetime('now','localtime') WHERE id = ?").run(userId || null, comment || '', articleId); const logId = uuidv4(); db.prepare('INSERT INTO review_log (id, article_id, reviewer_id, action, comment) VALUES (?, ?, ?, ?, ?)').run(logId, articleId, userId || null, 'reject', comment || ''); return { ok: true }; },
  getReviewLogs(articleId) { const db = getDb(); return db.prepare('SELECT * FROM review_log WHERE article_id = ? ORDER BY created_at DESC').all(articleId); },
  stats() { const db = getDb(); return { pending: db.prepare("SELECT COUNT(*) as c FROM articles WHERE status='review_pending'").get().c, rejected: db.prepare("SELECT COUNT(*) as c FROM articles WHERE status='review_rejected'").get().c }; }
};
