import os
import requests
import datetime
import random
import json

# ================= 配置区 =================
# 博客文章保存路径
POSTS_DIR = 'source/_posts'

# 如果本地运行没有环境变量，可以临时填在这里测试，但提交到 GitHub 时记得删掉！
API_KEY = os.environ.get("LLM_API_KEY")
BASE_URL = os.environ.get("LLM_BASE_URL", "https://api.deepseek.com")


# =========================================

def get_daily_english():
    """获取金山词霸每日一句 (作为轻松的开头)"""
    try:
        url = "http://open.iciba.com/dsapi/"
        res = requests.get(url, timeout=5).json()
        return res['content'], res['note'], res['picture2']
    except:
        return "Light is the shadow of God.", "光是上帝的影子。", ""


def generate_physics_problem():
    """调用 LLM 生成硬核物理/数学题"""
    if not API_KEY:
        return None, None

    # 决定今天的课题：70% 光学, 20% 微积分, 10% 概率论
    topics = ["Optics (Physics)"] * 7 + ["Calculus"] * 2 + ["Probability Theory"] * 1
    today_topic = random.choice(topics)

    # 构造 Prompt (提示词)
    system_prompt = "You are a rigorous physics and mathematics professor. You specialize in Optics."
    user_prompt = f"""
    Please generate a **thought-provoking problem** for me to solve today.

    **Requirements:**
    1. Subject: **{today_topic}**.
    2. Language: **English**.
    3. Content: The problem should be conceptual or calculation-based. It should be interesting and non-trivial.
    4. Format: 
       - First, present the **Problem** clearly.
       - Then, provide a detailed **Solution** and **Explanation**.

    **Output Format (JSON):**
    {{
        "topic": "{today_topic}",
        "question": "The question content...",
        "answer": "The detailed solution..."
    }}
    """

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    data = {
        "model": "deepseek-chat",  # 或者 "gpt-3.5-turbo"
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "response_format": {"type": "json_object"}  # 强制 JSON 格式，方便解析
    }

    try:
        response = requests.post(f"{BASE_URL}/chat/completions", headers=headers, json=data, timeout=30)
        result = response.json()
        content_str = result['choices'][0]['message']['content']
        content_json = json.loads(content_str)
        return content_json['topic'], content_json['question'], content_json['answer']
    except Exception as e:
        print(f"AI Generation Failed: {e}")
        # 备用：如果 AI 挂了，返回一个静态的兜底问题
        return "Optics", "Why is the sky blue?", "Rayleigh scattering..."


def create_markdown():
    today = datetime.date.today()
    date_str = today.strftime("%Y-%m-%d")

    # 1. 获取内容
    en_content, en_note, en_img = get_daily_english()
    topic, question, answer = generate_physics_problem()

    if not topic:
        print("No API Key found or generation failed. Skipping.")
        return

    # 2. 生成 Markdown
    # 注意：使用了 Hexo 的 {% fold %} 标签来折叠答案，防止一眼看到结果
    md_content = f"""---
title: "🧠 Daily Physics: {topic} | {date_str}"
date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
categories: 硬核日报
tags: [Physics, {topic}, English]
---

## ☕ Morning English
![]({en_img})
> **{en_content}**
> *{en_note}*

---

## ⚛️ Today's Challenge: {topic}

### ❓ Problem
{question}

---

### 💡 Solution & Analysis
<details>
<summary style="cursor: pointer; color: #2c3e50; font-weight: bold;">Click to reveal the solution</summary>

{answer}

</details>

---

*(Generated by AI Professor via GitHub Actions)*
"""

    # 3. 写入文件
    filename = f"{date_str}-physics.md"
    filepath = os.path.join(POSTS_DIR, filename)

    if not os.path.exists(filepath):
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        print(f"Successfully generated: {filename}")
    else:
        print("File already exists.")


if __name__ == "__main__":
    create_markdown()